from . import res_company
from . import res_config_settings
from . import product_template
from . import scaffold_stage
from . import scaffold_zone
from . import scaffold
from . import res_partner
from . import account_move
from . import project
from . import sale_order
from . import product_product
from . import account_analytic_line
